Repository Carolinaubes/pruebaGITsofiErianCaro, pull requests merged in 2025-04, with the labels that each got.

#1 Quiero meter txt's nuevos
  Eriansito.txt
  ejemplo1.py
Labels: enhancement

#3 Quiero subir este txt porfa
  Erian.txt
Labels: enhancement

#4 Verificacion cambios en el proyecto
  archivoNuevo.js
Labels: documentation

#5 Meter estilo
  ArchivoStyle.css
Labels: good first issue
